'use strict';

const config = require('@zone-eu/wild-config');
const { objectIdSchema } = require('../schemas/json-schemas');
const ObjectId = require('mongodb').ObjectId;
const CertHandler = require('../cert-handler');
const TaskHandler = require('../task-handler');
const tools = require('../tools');
const roles = require('../roles');
const { mongopagingFindWrapper } = require('../mongopaging-find-wrapper');

const certificateSchema = {
    type: 'string',
    wdEmpty: true,
    wdTrim: true,
    pattern: '^-+BEGIN CERTIFICATE-+\\s'
};

const privateKeySchema = {
    type: 'string',
    wdEmpty: true,
    wdTrim: true,
    pattern: '^-+BEGIN (RSA )?PRIVATE KEY-+\\s'
};

const certIdParam = objectIdSchema('ID of the TLS certificate', { wdRequired: true, examples: ['609d201236d1d936948f23b1'] });

module.exports = (db, server) => {
    const certHandler = new CertHandler({
        cipher: config.certs && config.certs.cipher,
        secret: config.certs && config.certs.secret,
        database: db.database,
        redis: db.redis,
        users: db.users,
        acmeConfig: config.acme
    });

    const taskHandler = new TaskHandler({
        database: db.database
    });

    server.route({
        method: 'GET',
        url: '/certs',
        schema: {
            summary: 'List registered TLS certificates',
            tags: ['Certs']
        },
        config: {
            name: 'getTLSCertificates',
            allowUnknown: true,
            validationObjs: {
                requestBody: {},
                queryParams: {
                    query: {
                        type: 'string',
                        maxLength: 255,
                        minLength: 1,
                        wdTrim: true,
                        wdEmpty: true,
                        description: 'Partial match of a server name',
                        examples: ['example.com']
                    },
                    altNames: {
                        $ref: 'wd:boolean',
                        default: false,
                        description: 'Match `query` value against SAN as well (including wildcard names)'
                    },
                    limit: { $ref: 'wd:pageLimit' },
                    next: {
                        $ref: 'wd:cursor',
                        description: 'Cursor value for next page, retrieved from nextCursor response value'
                    },
                    previous: {
                        $ref: 'wd:cursor',
                        description: 'Cursor value for previous page, retrieved from previousCursor response value'
                    },
                    sess: { $ref: 'wd:sess' },
                    ip: { $ref: 'wd:ip' }
                },
                pathParams: {},
                response: {
                    200: {
                        description: 'Success',
                        model: {
                            type: 'object',
                            title: 'GetTLSCertsResponse',
                            properties: {
                                success: { $ref: 'wd:successRes' },
                                query: { type: 'string', description: 'Initial query' },
                                total: { $ref: 'wd:totalRes' },
                                page: { $ref: 'wd:pageRes' },
                                previousCursor: { $ref: 'wd:previousCursorRes' },
                                nextCursor: { $ref: 'wd:nextCursorRes' },
                                results: {
                                    type: 'array',
                                    description: 'Certificate listing',
                                    items: {
                                        type: 'object',
                                        title: 'GetTLSCertResult',
                                        properties: {
                                            id: { type: 'string', description: 'ID of the certificate' },
                                            servername: { type: 'string', description: 'The server name this certificate applies to' },
                                            acme: {
                                                type: 'boolean',
                                                description: 'If true then private key and certificate are managed automatically by ACME'
                                            },
                                            description: { type: 'string', description: 'Key description' },
                                            fingerprint: { type: 'string', description: 'Key fingerprint (SHA1)' },
                                            created: { description: 'Datestring' },
                                            expires: { description: 'Certificate expiration time' },
                                            autogenerated: { type: 'boolean', description: 'Was the certificate automatically generated on SNI request' },
                                            altNames: {
                                                type: 'array',
                                                items: { type: 'string' },
                                                description: 'SAN servernames listed in the certificate'
                                            }
                                        },
                                        // altNames is echoed from the db document and may be absent
                                        // on records created before SAN support
                                        required: ['id', 'servername', 'acme']
                                    }
                                }
                            },
                            required: ['success', 'total', 'page', 'previousCursor', 'nextCursor', 'results']
                        }
                    }
                }
            }
        },
        async handler(req, reply) {
            const values = req.params;

            // permissions check
            req.validate(roles.can(req.role).readAny('certs'));

            let query = values.query;
            let altNames = values.altNames;
            let limit = values.limit;
            let pageNext = values.next;
            let pagePrevious = values.previous;

            let filter = query
                ? {
                      servername: {
                          $regex: tools.escapeRegexStr(query),
                          $options: ''
                      }
                  }
                : {};

            if (query && altNames) {
                filter = {
                    $or: [
                        filter,
                        {
                            altNames: {
                                $regex: tools.escapeRegexStr(query),
                                $options: ''
                            }
                        }
                    ]
                };

                if (query.indexOf('.') >= 0) {
                    let wcMatch = '*' + query.substr(query.indexOf('.'));
                    filter.$or.push({ altNames: wcMatch });
                }
            }

            let total = await db.database.collection('certs').countDocuments(filter);

            let opts = {
                limit,
                query: filter,
                paginatedField: 'servername',
                sortAscending: true
            };

            if (pageNext) {
                opts.next = pageNext;
            }
            if (pagePrevious) {
                opts.previous = pagePrevious;
            }

            let listingWrapper;
            try {
                listingWrapper = await mongopagingFindWrapper(db.database.collection('certs'), opts);
            } catch (err) {
                return reply.code(500).send({
                    error: 'MongoDB Error: ' + err.message,
                    code: 'InternalDatabaseError'
                });
            }

            let response = {
                success: true,
                query,
                total,
                page: listingWrapper.page,
                previousCursor: listingWrapper.previousCursor,
                nextCursor: listingWrapper.nextCursor,
                results: (listingWrapper.listing.results || []).map(certData => ({
                    id: certData._id.toString(),
                    servername: certData.servername,
                    description: certData.description,
                    fingerprint: certData.fingerprint || certData.fp,
                    expires: certData.expires,
                    autogenerated: certData.autogenerated,
                    altNames: certData.altNames,
                    acme: !!certData.acme,
                    created: certData.created
                }))
            };

            return reply.send(response);
        }
    });

    server.route({
        method: 'GET',
        url: '/certs/resolve/:servername',
        schema: {
            summary: 'Resolve ID for a server name',
            tags: ['Certs']
        },
        config: {
            name: 'resolveTLSCertificate',
            validationObjs: {
                requestBody: {},
                queryParams: {
                    sess: { $ref: 'wd:sess' },
                    ip: { $ref: 'wd:ip' }
                },
                pathParams: {
                    servername: {
                        type: 'string',
                        minLength: 1,
                        wdValidator: 'hostname',
                        wdRequired: true,
                        description: 'Server name',
                        examples: ['example.com']
                    }
                },
                response: {
                    200: {
                        description: 'Success',
                        model: {
                            type: 'object',
                            title: 'ResolveIdResponse',
                            properties: {
                                success: { $ref: 'wd:successRes' },
                                id: { type: 'string', description: 'Unique ID of the cert (24 byte hex)', examples: ['609d201236d1d936948f23b1'] }
                            },
                            required: ['success', 'id']
                        }
                    }
                }
            }
        },
        async handler(req, reply) {
            const values = req.params;

            // permissions check
            req.validate(roles.can(req.role).readAny('certs'));

            let servername = tools.normalizeDomain(values.servername);

            let certData;

            try {
                certData = await db.database.collection('certs').findOne(
                    {
                        servername
                    },
                    {
                        projection: { _id: 1 }
                    }
                );
            } catch (err) {
                return reply.code(500).send({
                    error: 'MongoDB Error: ' + err.message,
                    code: 'InternalDatabaseError'
                });
            }

            if (!certData) {
                return reply.code(404).send({
                    error: 'This servername does not exist',
                    code: 'CertNotFound'
                });
            }

            return reply.send({
                success: true,
                id: certData._id.toString()
            });
        }
    });

    server.route({
        method: 'POST',
        url: '/certs',
        schema: {
            summary: 'Create or update TLS certificate for server name',
            description:
                'Add a new TLS certificate for a server name or update existing one. You can add a single certificate for each server name but SAN names are supported as well. For example you can add a certificate for "mydomain.com" that includes "*.mydomain.com" in SAN and the same certificate would be used for requests that do not have it\'s own server name registered but match the SAN value.\n> NB! you must ensure yourself that the `servername` value is actually listed in certificate\'s common name or SAN as WildDuck is going to use this certificate regardless.',
            tags: ['Certs']
        },
        config: {
            name: 'updateTLSCertificate',
            validationObjs: {
                pathParams: {},
                queryParams: {},
                requestBody: {
                    servername: {
                        type: 'string',
                        minLength: 1,
                        wdEmpty: true,
                        wdValidator: 'hostname',
                        wdRequired: true,
                        description: 'Server name this TLS certificate applies to'
                    },

                    privateKey: Object.assign({}, privateKeySchema, {
                        description: 'PEM formatted TLS private key. Optional if certificate is managed by ACME'
                    }),

                    cert: Object.assign({}, certificateSchema, {
                        description:
                            'PEM formatted TLS certificate or a certificate bundle with concatenated certificate and CA chain. Optional if certificate is managed by ACME'
                    }),

                    ca: {
                        type: 'array',
                        items: certificateSchema,
                        description: 'CA chain certificates. Not needed if `cert` value is a bundle'
                    },

                    description: {
                        type: 'string',
                        maxLength: 1024,
                        minLength: 1,
                        wdEmpty: true,
                        wdTrim: true,
                        description: 'Certificate description'
                    },
                    acme: {
                        $ref: 'wd:boolean',
                        default: false,
                        description: 'If true then private key and certificate are managed automatically by ACME'
                    },

                    sess: { $ref: 'wd:sess' },
                    ip: { $ref: 'wd:ip' }
                },
                // Joi used privateKey/cert .when('acme', ...): both are
                // required unless the certificate is ACME managed
                conditions: [
                    {
                        if: { properties: { acme: { const: false } } },
                        then: { required: ['privateKey', 'cert'] }
                    }
                ],
                response: {
                    200: {
                        description: 'Success',
                        model: {
                            type: 'object',
                            title: 'UpdateTLSCertResponse',
                            properties: {
                                success: { $ref: 'wd:successRes' },
                                id: { type: 'string', description: 'ID of the certificate' },
                                servername: { type: 'string', description: 'The server name this certificate applies to' },
                                description: { type: 'string', description: 'Key description' },
                                fingerprint: { type: 'string', description: 'Key fingerprint (SHA1)' },
                                expires: { description: 'Certificate expiration time' },
                                altNames: {
                                    type: 'array',
                                    items: { type: 'string' },
                                    description: 'SAN servernames listed in the certificate'
                                },
                                acme: { type: 'boolean', description: 'If true then private key and certificate are managed automatically by ACME' }
                            },
                            required: ['success', 'id', 'servername', 'altNames', 'acme']
                        }
                    }
                }
            }
        },
        async handler(req, reply) {
            const values = req.params;

            // permissions check
            req.validate(roles.can(req.role).createAny('certs'));

            let response;

            try {
                response = await certHandler.set(values);
            } catch (err) {
                switch (err.code) {
                    case 'InputValidationError':
                        reply.code(400);
                        break;
                    case 'CertNotFound':
                        reply.code(404);
                        break;
                    default:
                        reply.code(500);
                }

                return reply.send({
                    error: err.message,
                    code: err.code
                });
            }

            if (response) {
                response.success = true;
            }

            if (values.acme) {
                await taskHandler.ensure('acme', { servername: values.servername }, { servername: values.servername });
            }

            return reply.send(response);
        }
    });

    server.route({
        method: 'GET',
        url: '/certs/:cert',
        schema: {
            summary: 'Request TLS certificate information',
            tags: ['Certs']
        },
        config: {
            name: 'getTLSCertificate',
            validationObjs: {
                requestBody: {},
                queryParams: {
                    sess: { $ref: 'wd:sess' },
                    ip: { $ref: 'wd:ip' }
                },
                pathParams: {
                    cert: certIdParam
                },
                response: {
                    200: {
                        description: 'Success',
                        model: {
                            type: 'object',
                            title: 'GetTLSCertResponse',
                            properties: {
                                success: { $ref: 'wd:successRes' },
                                id: { type: 'string', description: 'ID of the certificate' },
                                servername: { type: 'string', description: 'The server name this certificate applies to' },
                                description: { type: 'string', description: 'Key description' },
                                fingerprint: { type: 'string', description: 'Key fingerprint (SHA1)' },
                                expires: { description: 'Certificate expiration time' },
                                created: { description: 'Created datestring' },
                                autogenerated: { type: 'boolean', description: 'Was the certificate automatically generated on SNI request' },
                                altNames: {
                                    type: 'array',
                                    items: { type: 'string' },
                                    description: 'SAN servernames listed in the certificate'
                                },
                                acme: { type: 'boolean', description: 'If true then private key and certificate are managed automatically by ACME' },
                                hasCert: { type: 'boolean', description: 'True if certificate actually has the certificate or private key' }
                            },
                            required: ['success', 'id', 'servername', 'altNames', 'acme', 'hasCert']
                        }
                    }
                }
            }
        },
        async handler(req, reply) {
            const values = req.params;

            // permissions check
            req.validate(roles.can(req.role).readAny('certs'));

            let cert = new ObjectId(values.cert);

            let response;
            try {
                response = await certHandler.get({ _id: cert }, false);
            } catch (err) {
                switch (err.code) {
                    case 'InputValidationError':
                        reply.code(400);
                        break;
                    case 'CertNotFound':
                        reply.code(404);
                        break;
                    default:
                        reply.code(500);
                }

                return reply.send({
                    error: err.message,
                    code: err.code
                });
            }

            if (response) {
                response.success = true;
            } else {
                response.success = false;
            }

            return reply.send(response);
        }
    });

    server.route({
        method: 'DELETE',
        url: '/certs/:cert',
        schema: {
            summary: 'Delete a TLS certificate',
            tags: ['Certs']
        },
        config: {
            name: 'deleteTLSCert',
            validationObjs: {
                requestBody: {},
                queryParams: {
                    sess: { $ref: 'wd:sess' },
                    ip: { $ref: 'wd:ip' }
                },
                pathParams: {
                    cert: certIdParam
                },
                response: {
                    200: {
                        description: 'Success',
                        model: {
                            type: 'object',
                            title: 'SuccessResponse',
                            properties: {
                                success: { $ref: 'wd:successRes' }
                            },
                            required: ['success']
                        }
                    }
                }
            }
        },
        async handler(req, reply) {
            const values = req.params;

            // permissions check
            req.validate(roles.can(req.role).deleteAny('certs'));

            let cert = new ObjectId(values.cert);

            let response;

            try {
                response = await certHandler.del({ _id: cert });
            } catch (err) {
                switch (err.code) {
                    case 'InputValidationError':
                        reply.code(400);
                        break;
                    case 'CertNotFound':
                        reply.code(404);
                        break;
                    default:
                        reply.code(500);
                }

                return reply.send({
                    error: err.message,
                    code: err.code
                });
            }

            return reply.send({
                success: response
            });
        }
    });
};
