version: "3.7"
services:
    wildduck:
        restart: always
        image: ghcr.io/zone-eu/wildduck
        ports:
            - "8080:8080"
            - "143:143"
            - "110:110"
            - "993:993"
            - "995:995"
        depends_on:
            - redis
            - mongo
        environment:
            APPCONF_dbs_mongo: mongodb://mongo:27017/wildduck
            APPCONF_dbs_redis: redis://redis:6379/3
            APPCONF_api_host: 0.0.0.0
            APPCONF_api_accessToken: PLEASE_CHANGE_ME
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/db